config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  resources :mentors
  resources :students
  resources :registers, only: [:index]

  get '/all_registers', to: 'registers#all_registers', as: :all_registers

  root 'students#index'
end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :registers, dependent: :destroy
  has_many :students, through: :registers

  scope :eligible, -> (sat_score) {where('sat_min_score <= ?', sat_score)}
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  has_many :students
end

app/models/register.rb
class Register < ActiveRecord::Base
  belongs_to :student
  belongs_to :college
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :mentor

  has_many :registers, dependent: :destroy
  has_many :colleges, through: :registers

  def registered_college_ids
    self.colleges.pluck(:id).compact
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  def index
    @colleges = College.paginate(page: params[:page]).order(created_at: :desc)
  end

  def show
  end

  def new
    @college = College.new
  end

  def edit
  end

  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_college
      @college = College.find(params[:id])
    end


    def college_params
      params.require(:college).permit(:name, :country, :sat_min_score, :sat_max_score, :tuition_fees)
    end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: [:show, :edit, :update, :destroy]

  # GET /mentors
  # GET /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: 'Mentor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentor_params
      params.require(:mentor).permit(:name, :sex, :age, :dob, :bio, :image)
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController

  def index
  end

  def all_registers
    @registers = Register.includes(:student, :college).all
    result = @registers.map do |register|
      {
        student_name: register.student.name,
        student_sat_score: register.student.sat_score,
        college_name: register.college.name,
        college_fees: register.college.tuition_fees,
        registered_on: register.created_at.strftime("%d-%m-%Y")
      }
    end
    render json: result
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
    @registered_colleges = @student.colleges
  end

  def new
    @student = Student.new
    @colleges = College.all
  end

  def edit
    @registered_colleges = @student.registers.pluck(:college_id)
    @colleges = College.eligible(@student.sat_score)
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        create_registrations(@student, params[:collegeIds]) if params[:collegeIds].present?
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    college_ids = params[:collegeIds].present? ? params[:collegeIds].map(&:to_i) : []
    respond_to do |format|
      if @student.update(student_params)
        update_registrations(@student, college_ids)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :sex, :age, :dob, :current_school, :current_level, :country, :sat_score)
    end

    def create_registrations student, colleges
      colleges.each do |college|
        student.registers.create(:college_id => college.to_i)
      end
    end

    def update_registrations student, colleges
      new_colleges =  colleges - student.registered_college_ids
      deleted_colleges = student.registered_college_ids - colleges
      create_registrations(student, new_colleges) if new_colleges.present?

      if deleted_colleges.present?
        deleted_colleges.each do |college|
          student.registers.where(:college_id => college).destroy_all
        end
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-form flat" style="background-color: #fff;" >
    <div class="panel-body">
      <span>Name:</span>
      <%= f.text_field :name, :class => "form-control flat", :required => true %>
      <span>Country:</span>
      <%= f.text_field :country, :class => "form-control flat", :required => true %>
      <span>Sat Minimum Score:</span>
      <%= f.number_field :sat_min_score, :class => "form-control flat", :required => true %>
      <span>Sat Maximum Score:</span>
      <%= f.number_field :sat_max_score, :class => "form-control flat", :required => true %>
      <span>Tuition Fees:</span>
      <%= f.number_field :tuition_fees, :class => "form-control flat", :required => true %>
      <%= f.submit class: "btn btn-danger btn-panel"%>
      <%= link_to 'Cancel', colleges_path %>
    </div>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Edit details for <%= @college.name %> </h3>
    <%= render 'form' %>
  </div>
</div>

app/views/colleges/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
    <div class="panel panel-default panel-custom">
      <div class="panel-heading">Listing Colleges
        <%= link_to 'New College', new_college_path, class: "pull-right btn-sm btn-danger btn-panel" %>
      </div>
      <div class="panel-body">
        <% unless @colleges.present? %>
          <h3>There are no College records available.</h3>
        <% else %>
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Country</th>
                <th>Sat min score</th>
                <th>Sat max score</th>
                <th>Tuition fees</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @colleges.each do |college| %>
                <tr>
                  <td><%= link_to college.name, college %></td>
                  <td><%= college.country %></td>
                  <td><%= college.sat_min_score %></td>
                  <td><%= college.sat_max_score %></td>
                  <td><%= college.tuition_fees %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @colleges %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/colleges/new.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Create New College:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/colleges/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default lifted-box flat">
        <div class="panel-heading">
          <h4>Showing details of <%= @college.name %></h4>
        </div>
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>Name:</td>
              <td><%= @college.name %></td>
            </tr>
            <tr>
              <td>Country:</td>
              <td><%= @college.country %></td>
            </tr>
            <tr>
              <td>Sat min score:</td>
              <td><%= @college.sat_min_score %></td>
            </tr>
            <tr>
              <td>Sat max score:</td>
              <td><%= @college.sat_max_score %></td>
            </tr>
            <tr>
              <td>Tuition fees:</td>
              <td><%= @college.tuition_fees %></td>
            </tr>
          </table>
        </div>
        <div class="panel-footer">
          <a href=<%= colleges_path %>><i class="fa fa-arrow-circle-o-left fa-3"></i></a>
          <a href=<%= edit_college_path(@college) %>><i class="fa fa-pencil-square-o fa-3"></i></a>
          <a href=<%= @college %> data-method="delete" rel="nofollow" data-confirm="Are you sure?"><i class="fa fa-trash-o"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ENROLL', root_path, class: 'navbar-brand navlink' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Students', students_path, class: 'navlink' %></li>
        <li><%= link_to 'Colleges', colleges_path, class: 'navlink' %></li>
        <li><%= link_to 'Mentors', mentors_path, class: 'navlink' %></li>
        <li><%= link_to 'Registrations', registers_path, class: 'navlink' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enroll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/header' %>
<div class="container-fluid">
<%= flash_messages %>
<%= yield %>
</div>
</body>
</html>

app/views/mentors/_form.html.erb
<%= form_for(@mentor) do |f| %>
  <% if @mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
      <% @mentor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-form flat" style="background-color: #fff;" >
    <div class="panel-body">
      <span>Name:</span>
      <%= f.text_field :name, :class => "form-control flat", :required => true %>
      <span>Sex:</span>
      <%= f.text_field :sex, :class => "form-control flat", :required => true %>
      <span>DOB:</span>
      <%= f.text_field :dob, :class => "form-control flat", :required => true, id: 'dob_field' %>
      <span>Age:</span>
      <%= f.number_field :age, :class => "form-control flat", :required => true, id: 'age_field' %>
      <span>Bio:</span>
      <%= f.text_field :bio, :class => "form-control flat", :required => true %>
      <span>Image:</span>
      <%= f.text_field :image, :class => "form-control flat", :required => true %>
      <%= f.submit class: "btn btn-danger btn-panel" %>
    </div>
  </div>
<% end %>

app/views/mentors/edit.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Edit details for <%= @mentor.name %>:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/mentors/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
    <div class="panel panel-default panel-custom">
      <div class="panel-heading">Listing Mentors
        <%= link_to 'New Mentor', new_mentor_path, class: "pull-right btn-sm btn-danger btn-panel" %>
      </div>
      <div class="panel-body">
        <% unless @mentors.present? %>
          <h3>There are no Mentor records available.</h3>
        <% else %>
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Sex</th>
                <th>Age</th>
                <th>Dob</th>
                <th>Bio</th>
                <th>Image</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @mentors.each do |mentor| %>
                <tr>
                  <td><%= link_to mentor.name, mentor %></td>
                  <td><%= mentor.sex %></td>
                  <td><%= mentor.age %></td>
                  <td><%= mentor.dob %></td>
                  <td><%= mentor.bio %></td>
                  <td><%= mentor.image %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/mentors/new.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Create New Mentor:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/mentors/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default lifted-box flat">
        <div class="panel-heading">
          <h4>Showing details of <%= @mentor.name %></h4>
        </div>
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>Name:</td>
              <td><%= @mentor.name %></td>
            </tr>

            <tr>
              <td>Sex:</td>
              <td><%= @mentor.sex %></td>
            </tr>

            <tr>
              <td>Age:</td>
              <td><%= @mentor.age %></td>
            </tr>

            <tr>
              <td>Dob:</td>
              <td><%= @mentor.dob %></td>
            </tr>

            <tr>
              <td>Bio:</td>
              <td><%= @mentor.bio %></td>
            </tr>

            <tr>
              <td>Image:</td>
              <td><%= @mentor.image %></td>
            </tr>
          </table>
        </div>
        <div class="panel-footer">
          <a href=<%= mentors_path %>><i class="fa fa-arrow-circle-o-left fa-3"></i></a>
          <a href=<%= edit_mentor_path(@mentor) %>><i class="fa fa-pencil-square-o fa-3"></i></a>
          <a href=<%= @mentor %> data-method="delete" rel="nofollow" data-confirm="Are you sure?"><i class="fa fa-trash-o"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/registers/index.html.erb
<input type="hidden" id="driver" data-remote=<%= all_registers_path %>>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-custom">
        <div class="panel-heading">All Registrations</div>
        <div class="panel-body">
          <table class="table" id="registers_table">
            <thead>
              <th>Student Name</th>
              <th>Student Sat Score</th>
              <th>College Name</th>
              <th>College Fees</th>
              <th>Registered on</th>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-form flat" style="background-color: #fff;" >
    <div class="panel-body">
        <span>Name:</span>
        <%= f.text_field :name, :class => "form-control flat", :required => true %>
        <span>Sex:</span>
        <%= f.text_field :sex, :class => "form-control flat", :required => true %>
        <span>Date of Birth:</span>
        <%= f.text_field :dob, :class => "form-control flat", :required => true, id: 'dob_field' %>
        <span>Age:</span>
        <%= f.number_field :age, :class => "form-control flat", :required => true, id: 'age_field' %>
        <span>Current School:</span>
        <%= f.text_field :current_school, :class => "form-control flat", :required => true %>
        <span>Current Level:</span>
        <%= f.text_field :current_level, :class => "form-control flat", :required => true %>
        <span>Country:</span>
        <%= f.text_field :country, :class => "form-control flat", :required => true %>
        <span>Sat Score:</span>
        <%= f.number_field :sat_score, :class => "form-control flat", :required => true %>
        <span>Colleges:</span>
        <%= select_tag "collegeIds", options_from_collection_for_select(@colleges, "id", "name", @registered_colleges), :include_blank => true, :class => "form-control flat", :multiple => 'multiple', :multiple => true %>
      <div class="actions">
        <%= f.submit class: "btn btn-danger btn-panel" %>
        <%= link_to 'Cancel', students_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Edit <%= @student.name %> details:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/students/index.html.erb
<div class="container-fluid">
  <div class="row">
  <div class="col-md-12">
  <div class="panel panel-default panel-custom">
    <div class="panel-heading">Listing Students
      <%= link_to 'New Student', new_student_path, class: "pull-right btn-sm btn-danger btn-panel" %>
    </div>
    <div class="panel-body">
      <% unless @students.present? %>
        <h3>There are no student records available.</h3>
      <% else %>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Sex</th>
              <th>Age</th>
              <th>Dob</th>
              <th>Current school</th>
              <th>Current level</th>
              <th>Country</th>
              <th>Sat score</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @students.each do |student| %>
              <tr>
                <td><%= link_to student.name, student %></td>
                <td><%= student.sex %></td>
                <td><%= student.age %></td>
                <td><%= student.dob %></td>
                <td><%= student.current_school %></td>
                <td><%= student.current_level %></td>
                <td><%= student.country %></td>
                <td><%= student.sat_score %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

<br>

app/views/students/new.html.erb
<div class="container">
  <div class="lifted-box col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <h3>Create New Student:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/students/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default lifted-box flat">
        <div class="panel-heading">
          <h4>Showing details of <%= @student.name %></h4>
        </div>
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>Name:</td>
              <td><%= @student.name %></td>
            </tr>

            <tr>
              <td>Sex:</td>
              <td><%= @student.sex %></td>
            </tr>

            <tr>
              <td>Age:</td>
              <td><%= @student.age %></td>
            </tr>

            <tr>
              <td>Dob:</td>
              <td><%= @student.dob %></td>
            </tr>

            <tr>
              <td>Current school:</td>
              <td><%= @student.current_school %></td>
            </tr>

            <tr>
              <td>Current level:</td>
              <td><%= @student.current_level %></td>
            </tr>

            <tr>
              <td>Country:</td>
              <td><%= @student.country %></td>
            </tr>

            <tr>
              <td>Sat score:</td>
              <td><%= @student.sat_score %></td>
            </tr>
          </table>
        </div>
        <div class="panel-footer">
          <a href=<%= students_path %>><i class="fa fa-arrow-circle-o-left fa-3"></i></a>
          <a href=<%= edit_student_path(@student) %>><i class="fa fa-pencil-square-o fa-3"></i></a>
          <a href=<%= @student %> data-method="delete" rel="nofollow" data-confirm="Are you sure?"><i class="fa fa-trash-o"></i></a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel lifted-box panel-custom flat">
        <div class="panel-heading flat">
          Applied Colleges:
        </div>
        <div class="panel-body flat">
          <ul class="list-group">
            <% @registered_colleges.each do |college| %>
              <li class="list-group-item">
                <span class="badge"><%= college.registers.count %></span>
                <%= link_to college.name, college_path(college) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>